# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Scipp contributors (https://github.com/scipp)

class Coords: ...
class DataArray: ...
class Dataset: ...
class DType: ...
class GroupByDataArray: ...
class GroupByDataset: ...
class Masks: ...
class Unit: ...
class Variable: ...

class BinEdgeError(RuntimeError): ...
class BinnedDataError(RuntimeError): ...
class CoordError(RuntimeError): ...
class DataArrayError(RuntimeError): ...
class DatasetError(RuntimeError): ...
class DimensionError(RuntimeError): ...
class DTypeError(TypeError): ...
class SizeError(RuntimeError): ...
class SliceError(IndexError): ...
class UnitError(RuntimeError): ...
class VariableError(RuntimeError): ...
class VariancesError(RuntimeError): ...
