package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - gxx_linux-64 7.3.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - tbb-devel [linux64]
  run:
    - appdirs
    - numpy >=1.15.3
    - python {{ python }}
    - python-configuration
    - pyyaml
    - tbb [linux64]

test:
  import:
    - scipp
  requires:
    - beautifulsoup4
    - ipyevents
    - ipyvolume
    - ipywidgets
    - matplotlib
    - psutil
    - pytest
    - pythreejs
  source_files:
    - python/tests
  commands:
    - python -m pytest -v python

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - CC
    - CXX
    - OSX_VERSION

about:
  home: https://scipp.github.io/
  license: GPLv3
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
