# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Scipp contributors (https://github.com/scipp)

# Note:
#
# The conda documentation recommends placing version number in the
# conda_build_config.yaml file, instead of directly in this meta.yaml file:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
# It seems the primary advantage of doing this is that it allows matrix builds from a
# single conda-build command.
# For now, the only matrix-style building we are doing is the python version,
# which is set via the `--python` command line argument anyway, because we are
# parallelising our CI builds.
# A matrix build from conda-build directly would have to perform the lib solving for
# each version, and using multiple workers on our CI is faster than building all python
# versions in a single conda-build step.

package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - {{ compiler('cxx') }} [not win]
    - cmake
    - cppcheck [linux64]
    - conan>=1.45.0
    - markupsafe>=1.1.1,<2.1.0  # see https://github.com/pallets/markupsafe/issues/284
    - git
    - ninja
  host:
    - python
    - tbb-devel=2020.2.*
  run:
    - confuse
    - numpy>=1.20.0
    - python
    - pyyaml
    - tbb=2020.2.*
    - graphlib-backport # for python < 3.9

test:
  imports:
    - scipp
  requires:
    - cmake
    - conan>=1.45.0
    - markupsafe>=1.1.1,<2.1.0  # see https://github.com/pallets/markupsafe/issues/284
    - h5py
    - hypothesis
    - ipympl
    - ipywidgets
    - markupsafe>=1.1.1,<2.1.0  # see https://github.com/pallets/markupsafe/issues/284
    - matplotlib-base
    - pytest
    - pythreejs
    - python-graphviz
    - xarray
    - pandas
    - scipy>=1.7.0
  files:
    - cmake-package-test/
  source_files:
    - tests/
  commands:
    - python -m pytest -v tests
    - python cmake-package-test/build.py

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script:
    - cmake --preset package-linux -DPython_EXECUTABLE=$PYTHON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX [linux]
    - cmake --preset package-macos -DPython_EXECUTABLE=$PYTHON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX [osx]
    - cmake --preset package-windows -DPython_EXECUTABLE=$PYTHON -DCMAKE_PREFIX_PATH=$CONDA_PREFIX [win]
    - cmake --build --preset build
    #- ctest --preset test

about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
