package:
  name: scipp
  # Get version number from most recent Git tag
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - gxx_linux-64 9.3.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - tbb-devel
  run:
    - appdirs
    - numpy >=1.15.3
    - python {{ python }}
    - python-configuration
    - pyyaml
    - tbb

test:
  import:
    - scipp
  requires:
    - h5py
    - ipywidgets
    - matplotlib-base
    - pytest
    - pythreejs
    - python-graphviz
    - xarray
    - pandas
  source_files:
    - python/tests
  commands:
    - python -m pytest -v python

build:
  # Build number is number of Git commits since last tag, if that fails use 0
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - SCIPP_INSTALL_PREFIX
  script:
    - python tools/build_conda.py


about:
  home: https://scipp.github.io/
  license: BSD-3-Clause
  summary: Multi-dimensional data arrays with labeled dimensions
  description: Multi-dimensional data arrays with labeled dimensions
  dev_url: https://github.com/scipp/scipp
  doc_url: https://scipp.github.io/
