function(scipp_function function_name category)
  set(NAME ${function_name})
  set(ELEMENT_INCLUDE ${category})
  set(inc include/scipp/variable/${NAME}.h)
  set(src ${NAME}.cpp)
  configure_file(variable/include/scipp/variable/unary_function.h.in variable/${inc})
  configure_file(variable/unary_function.cpp.in variable/${src})
  set(variable_INC_FILES ${variable_INC_FILES} ${inc} PARENT_SCOPE)
  set(variable_SRC_FILES ${variable_SRC_FILES} ${src} PARENT_SCOPE)
endfunction()
